package groxy

var pages []string = []string{"https://play.golang.org", "https://www.proxy-checker.org/",
	"https://support.paloaltonetworks.com/Support/Index", "https://www.glocksoft.com/", "https://hidemyna.me/en/",
	"https://support.umbrella.com/hc/en-us", "https://wiki.ubuntu.com/", "https://www.chromium.org/", "https://soundcloud.com/",
	"https://www.wikipedia.org/", "https://checkerproxy.net/", "https://www.infobyip.com/", "https://proxy6.net/en/",
	"https://hidester.com/", "http://www.all-nettools.com/index.htm", "http://www.httptunnel.ge/ProxyChecker.aspx",
	"http://www.toolsvoid.com/proxy-test", "https://www.proxynova.com/online-proxy-checker/", "https://www.iplocation.net/proxy-check",
	"https://www.proxysite.com/", "https://www.ipqualityscore.com/free-ip-lookup-proxy-vpn-test", "https://www.portcheckers.com/proxy-checker",
	"https://ping.eu/proxy/", "http://amibehindaproxy.com/", "https://gogetproxy.com/en/checker", "https://free-proxy-list.net/", "https://www.kproxy.com/",
	"https://wonderproxy.com/", "https://whoer.net/", "https://mitmproxy.org/", "https://www.proxyrack.com/", "https://code.visualstudio.com/",
	"https://www.makeuseof.com/", "https://www.imdb.com/", "https://www.indiewire.com/", "https://finance.yahoo.com/", "https://qz.com/quartzy/",
	"https://www.apple.com/ios/app-store/", "http://digg.com/", "https://www.scoop.it/", "https://weheartit.com/", "https://getpocket.com/",
	"https://www.bizsugar.com/", "https://www.npmjs.com/package/pkg", "https://maven.apache.org/", "https://pypi.org/", "https://www.godaddy.com/",
	"https://www.namecheap.com/", "https://www.wix.com/", "https://lunarpages.com/", "https://pair.com/", "https://www.hostdime.com/",
	"https://www.interserver.net/", "https://freewebs.com/", "https://myhosting.com/", "https://www.moonfruit.com/", "https://www.ipower.com/",
	"https://www.netfirms.com/", "https://www.nexcess.net/", "https://www.web.com/", "http://he.net/", "https://www.bluehost.com/",
	"https://www.hostgator.com/", "https://www.ipage.com/", "http://www.webhostingtalk.com/", "https://www.inmotionhosting.com/",
	"https://www.dreamhost.com/", "https://www.siteground.com/", "https://www.reverbnation.com/", "https://www.dropbox.com/",
	"https://github.com/", "https://medium.com/", "https://getbootstrap.com/", "https://www.w3schools.com/", "https://www.tutorialrepublic.com/",
	"https://stackoverflow.com/", "https://www.geeksforgeeks.org/", "https://www.huffpost.com/", "https://www.worldstarhiphop.com/videos/",
	"https://www.eonline.com/", "https://www.bet.com/", "https://www.tmz.com/", "https://people.com/", "https://hollywoodlife.com/",
	"https://mtonews.com/", "https://theshaderoom.com/", "http://www.filmfare.com/", "https://www.lifeandstylemag.com/", "https://www.bollywoodlife.com/",
	"https://www.usmagazine.com/", "https://www.glamourmagazine.co.uk/", "https://www.aol.com/", "https://www.vanityfair.com/",
	"https://www.intouchweekly.com/", "https://www.popsugar.com/celebrity/", "http://www.zimbio.com/", "https://www.entertainmentdaily.co.uk/",
	"https://perezhilton.com/", "https://www.hellomagazine.com/", "https://www.accessonline.com/", "https://www.celebuzz.com/",
	"https://www.pinkvilla.com/", "https://www.thehollywoodgossip.com/", "https://www.buzzfeed.com/celebrity", "https://bollywoodjournalist.com/",
	"https://deadline.com/", "https://globalnews.ca/", "https://celebrity.nine.com.au/", "https://celebrityinsider.org/", "https://radaronline.com/",
	"https://toofab.com/", "https://bossip.com/", "https://www.celebitchy.com", "http://www.wetpaint.com/", "https://www.ok.co.uk/", "http://extratv.com/",
	"http://www.latina.com/", "http://vipmagazine.ie/"}
